guardian/braze-components

- .github/workflows/test.yml
- .gitignore
- .storybook/main.js
- package.json
- src/DigitalSubscriberAppBanner.stories.tsx
- yarn.lock
Sets up the integration with Chromatic so we get a hosted Storybook.
> Setup Chromatic integration

- src/DigitalSubscriberAppBanner.stories.tsx
- src/DigitalSubscriberAppBanner.tsx
An update to the dynamic text field which will have more relevance to the end goal (a message into which marketing can input).
Also a small improvement to our JSX indentation.
Run `yarn storybook` and check the component in-situ
> Dynamic fields improvements

- src/DigitalSubscriberAppBanner.tsx
In terms of their impact on moving through the canvas in Braze, we want to treat "OK, got it" and "I'm not interested" the same.
> Make the two main buttons behave the same

- artifact.json
- riff-raff.yaml
Added CloudFormation deployment to RiffRaff.
This will cause RiffRaff to trigger CloudFormation updates as part of the deploy process.
> Added CloudFormation deployment to RiffRaff

- .storybook/grid/GridPanel.tsx
- .storybook/utils.ts
- src/utils/env.ts
- src/utils/images.test.ts
Replaced NODE_ENV environment query with hostname-based solution
Abstracts over dev, code and production environment queries.
Also surfaces isCode and isProduction methods in advance of login PR.
(Testing in progress)
> Replaced NODE_ENV environment query with hostname-based solution

- README.md
- package.json
- yarn.lock
Other folks at The Guardian have been using [`np`](https://github.com/sindresorhus/np) to publish to NPM and it provides some [nice features](https://github.com/sindresorhus/np#why) over using plain `yarn publish`.
> Use np to publish

- package.json
Fix a couple of small issues which came up when publishing with np for the first time.
> Small fixes for np publishing

- babel.config.json
- package.json
- yarn.lock
Update react to v17
We want to support JSX
Tested on the platforms by forcing the banner with `#force-braze-message`.
Frontend:
DCR:
> Update React 17

- src/logic/LocalMessageCache.test.ts
- src/logic/LocalMessageCache.tsx
all method to allow getting multiple valid messages from the local message cache queue.
> all method to get all messages from local message cache queue

- package.json
- yarn.lock
Remove `preact-x` dependency
No longer used
> Remove Preact-X

- .github/workflows/typescript.yml
Add TypeScript build check.
A new build check in the GitHub UI - `typescript / typescript (push)`.
> Add TypeScript build check

- src/BrazeMessageComponent.tsx
- src/USNewsletterEpic/canRender.ts
- src/USNewsletterEpic/index.stories.tsx
- src/USNewsletterEpic/index.tsx
- src/canRender.ts
Start of US Newsletter Epic.
Trello Card: https://trello.com/c/csMyMtNN/1162-static-version-of-us-first-thing-newsletter-epic﻿
> US Newsletter Epic component

- src/Epic/index.stories.tsx
- src/Epic/index.tsx
Adds support for HTML in the `Epic` `highlightedText` prop. One of our canvases has HTML in here (a link) so we need to support this.
`yarn storybook`.
> Support HTML in Epic highlightedText prop

- README.md
Updates the README for the project.
> Show the docs some ❤️ 

- cdk/lib/__snapshots__/braze-components.test.ts.snap
- cdk/lib/braze-components.ts
Reduce the TTL of the DNS entry in order to make is safer/faster to make changes.
> Reduce DNS TTL

- cdk/package.json
- cdk/yarn.lock
Upgrade dependencies of the cdk sub-project within the range of what's specified in the `package.json`.
Synthing the CDK still works:
`$ yarn synth`
The snapshot test passes:
`$ yarn test`
> Safe upgrade gu/cdk dependencies

- cdk/yarn.lock
Bump `parse-url` library to 6.0.5.
The version of this library we were using has a security vulnerability so bump to a version where the vulnerability is fixed.
> Upgrade parse-url

- .github/workflows/braze-components.yml
Fix the build. We started seeing errors in the build on the build-storybook step which look like they're related to the Node version according to Google:
`Error: error:0308010C:digital envelope routines::unsupported`
It turns out we weren't honouring the .nvmrc since migrating to GitHub actions for the build. Updating the workflow to correctly use the .nvmrc seems to get things working.
-   [ ] …
> Fix the build

- .github/workflows/snyk.yml
* Updates the Snyk org to the Supporter Revenue org
* Adds the Marketing Tools label in Snyk
> Snyk improvements

- cdk/yarn.lock
Upgrade the semver NPM package. Snyk has reported a vulnerability. There are a few different major versions in the bundle as transitive dependencies of other packages. This upgrades all of them to versions in which the vulnerability has been fixed.
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md# …
> Upgrade semver NPM packages

- .github/workflows/braze-components.yml
This separates out what is currently one workflow step into two:
* Run jest tests, linting etc
* Build the hosted storybook and upload to Riff Raff
> Split the tests etc from the storybook build

- README.md
Updates the docs to describe the process of releasing to NPM. We've migrated to changesets and releasing from CI (see also #435 and #436).
> Update README to describe new release process

- cdk/yarn.lock
Dependabot is reporting a vulnerability for lower versions than this.
See also #468.
> Upgrade @babel/traverse in CDK project

- .changeset/tall-planes-glow.md
- .eslintrc.js
- .storybook/preview.js
- package.json
- src/AppBanner/index.tsx
- src/Epic/HeaderSection.tsx
- src/Epic/index.tsx
- src/NewsletterEpic/index.tsx
- src/StyleableBannerNewsletter/index.tsx
- src/StyleableBannerWithLink/index.tsx
- src/components/BannerCloseButton.tsx
- src/components/NewsletterCtaButton.tsx
- src/components/NewsletterFrequencyBlock.tsx
- src/components/PaymentIcons.tsx
- src/components/PrimaryCtaButton.tsx
- src/components/ReminderCtaButton.tsx
- src/styles/colorData.ts
- yarn.lock
`@guardian/source` packages have been renamed/re-structured, but are functionally equivalent.
Note: I started migrating over to the new development kitchen package, but it turns out it's no longer used so I've removed it instead.
Check that storybook is happy (there are equivalent stories in DCR too so we get this extra verification at the point of consumption). There are some unrelated Chromatic changes to accept (rolling over to a new month is reflected in the reminder button), I'll wait to approve until just before merging.
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboa …
> New source packages

- .github/workflows/braze-components.yml
Create and upload Riff Raff artefacts for dependabot PRs.
I missed this in #481.
> Upload to Riff Raff for dependabot PRs

- package.json
- yarn.lock
Remove the `np` package. It's no longer used, since we moved to changesets
> Remove `np` package

- cdk/yarn.lock
Affects < 1.0.2, reported by dependabot.
> Fix vulnerability in json5 v1

- yarn.lock
Bump minimatch (a transitive dependency of storybook). Dependabot flagged a vulnerability in versions < 3.0.5.
> Bump minimatch

- yarn.lock
Bump the terser npm package. Dependabot reported a vulnerability across different versions.
~~Note: the base is #494.~~
> Bump terser NPM package

- yarn.lock
Upgrade nth-check NPM package as Dependabot reported a vulnerability.
> Upgrade nth-check NPM package

- package.json
- yarn.lock
Upgrade `rollup-plugin-filesize` to 10.x.x. Even though this is a major version bump, it seems to work in a backwards compatible way - the file size reporting when running `yarn build` looks the same.
Doing this because it removes one of the paths causing us to pull in the ip package, which currently has an unpatchable vulnerability.
-   [ ] [The change doesn't use only colour to convey …
> Upgrade rollup-plugin-filesize

- .changeset/thirty-ducks-dream.md
- CHANGELOG.md
- jest.config.js
- package.json
- src/logic/BrazeCards.test.ts
- src/logic/BrazeCards.ts
- src/logic/BrazeMessages.test.ts
- src/logic/BrazeMessages.ts
- src/logic/LocalMessageCache.test.ts
- src/logic/LocalMessageCache.tsx
- yarn.lock
This pull request upgrades @braze/web-sdk-core from version 3.5.1 to @braze/web-sdk version 5.8.1. The change is reflected in the package and documented in the CHANGELOG.md. Additionally, updates have been made to jest.config.js to refine module transformation patterns. More detail could be read [here](https://trello.com/c/213tggX9/749-braze-v5-for-braze-components).
The "cardId" and "campaignId" properties of In-App Messages were [removed](https://github.com/braze-inc/braze-web-sdk/blob/master/UPGRADE_GUIDE.md#removed-apis-1) on the newer versions of this SDK.
To avoid data loss, I'm moving them into "extras" property to keep the same data as before.
1. Run npm install to ensure dependencies are updated.
2. Execute npm test to verify that all unit tests pass successfully.
3. Perform a …
> @braze/web sdk v3 to v4 to v5
