guardian/braze-components

package.json
src/DigitalSubscriberAppBanner.stories.tsx
src/DigitalSubscriberAppBanner.tsx

I've changed the integers in strings used as button IDs to be pure numbers - once called in Frontend or DCR, the InAppMessageButtonClick constructor expects a number, so providing a number-typed value here saves us work in the repositories where the component is used.
I've also updated the case of the property names displayed in Storybook (i.e. "header", "body") to be lower case, in order to exactly match their names in the Braze interface.
The component can be tested in Storybook using `yarn storybook`.

Buttons IDs and property name consistency

---

.storybook/main.js
.storybook/preview.js
package.json
yarn.lock

Adds easy switching between source viewport widths to Storybook (viewport config taken from the support-dotcom-components project).

Add Guardian breakpoints to Storybook

---

package.json
src/DigitalSubscriberAppBanner.tsx

The `closeButton` is now keyboard focusable, showing the focusHalo when navigated to using the tab key. For now, the tabindex has been set to 0, but could be increased based on feedback from the E&P/Accessibility group.
There is an open question of how the banner should be navigated to - screen-reader users may find the banner unobtrusive as it is (because it's sequentially after the main page content), while users navigating by keyboard may want to close it without tabbing through the rest of the page.
View in storybook by running `yarn storybook`.

Accessibility improvements

---

package.json
src/DigitalSubscriberAppBanner.tsx
src/utils/styleUtilities.ts

- Palette and font changes in response to new designs.
- Modifications to Tablet layout - now similar to Phablet layout (i.e. no image) as the image was too cramped in this layout.
- Addition of screenshot from Grid.
- Close button now based on source component, rather than custom button build from source svg (focusHalo no longer needs to be explicitly added for focus)
- Addition of GT Titlepiece font to the repo in order to support future use.
Run `yarn storybook` to see the component in situ.
****

Changes related to new design

---

.editorconfig
.eslintrc.js
.prettierrc.js
index.ts
package.json
src/DigitalSubscriberAppBanner.stories.tsx
src/DigitalSubscriberAppBanner.tsx
yarn.lock

I noticed that the formatting my editor was applying was different than the recent commits made by Rhys. It turned out that we didn’t have eslint and prettier config for this repo. Added and reformatted the main component and story. Slightly annoying to have to do this because the diff is noisy, but better now than down the line when we're supporting more components.
There should be no user-visible changes from this PR.

Get eslint & prettier working consistently

---

package.json
rollup.config.js

Publish our package as an ES module
This is the [approach we’re settling on in Client Side infra discussions](https://github.com/orgs/guardian/teams/client-side-infra/discussions/11).
Furthermore, without this change the module no longer loads correctly on frontend since guardian/frontend#23011 was merged, which changes the config to transpile all @guardian NPM packages.
Here's the banner component loading successfully on DCR and frontend (I've forced the component to load, rather than triggering from Braze, which is why the copy is wrong):

Publish Package as an ES Module

---

package.json
rollup.config.js

This switches to publishing the package as esm and cjs. I followed the example of the cmp library. When only publishing as esm I ran into an issue where the linter was failing the find the package on the platforms. This seems to fix the issue.
Note that in order to test this I published the package off of this branch (`0.0.10`).

Publish package as esm and cjs

---

src/DigitalSubscriberAppBanner.tsx

A small fix for IE11 and Edge, keeping the primary image in correct dimensions and keeping the app store icons inline.

Added css fix for IE11 and Edge

---

README.md

Added some useful info for testing in Frontend regarding `make watch` tracking the linked module.
Also added an instruction for updating `main` when a new version of the NPM module is published.

Updated README to include more information on testing and updating the NPM module.

---

.gitignore
package.json
rollup.config.js
yarn.lock

This outputs a `stats.html` file when building the package so we can see what our bundle is made up of.
Also includes a tidy up of the rollup config (separate commit).

Add Rollup Visualizer Plugin

---

.github/dependabot.yml

Enables [dependabot](https://dependabot.com/) for this repo, to keep our dependencies up to date.

Enable dependabot for braze-components

---

package.json
src/BrazeMessage.test.tsx
src/BrazeMessage.tsx
src/DigitalSubscriberAppBanner.stories.tsx
src/DigitalSubscriberAppBanner.test.tsx
src/DigitalSubscriberAppBanner.tsx
src/tracking.ts
yarn.lock

The platform is expected to provide an implementation of `submitComponentEvent` to the component as a prop. We can then use this whenever we want to add Ophan tracking in the component. Initially we'll be using it for tracking clicks. This This reduces duplication and arguably makes it easier to test.
Note that I'm pointing to a GitHub branch for `@guardian/types` to get the Ophan types. When (if!) that branch is merged we can switch to getting from NPM.

Handle click tracking in the component

---

.gitignore
Brewfile
README.md
bin/setup
nginx/nginx-mappings.yml
package.json

Add support for running Storybook locally on a gutools domain. This is so that we can embed Grid into the story for image handling (coming in a future PR).
* Run storybook locally
* Visit https://braze-storybook.local.dev-gutools.co.uk/
* There are still some items to figure out which we can tackle in future PRs. We'll want to access the deployed version of Storybook via a gutools domain too (and this will need to embed prod Grid). Probably by building storybook and deploying to an S3 bucket.
* Running `yarn storybook` still opens http://localhost:6016. This is because it's non-trivial to override the URL which storybook opens in the browser. You can tell Storybook not to open in a browser with the `--ci` flag, but because the Storybook server is a daemon it's hard to know when to then …

Run Local Storybook on a gutools domain

---

.storybook/gu-preview/GuPreview.tsx

We no longer support using www so use preview instead.
See guardian/frontend#23311 and guardian/dotcom-rendering#2148.
The little preview icon in storybook should now link to an article on preview.gutools.co.uk instead of www.theguardian.com.

Update URL we use to preview the banner

---

.storybook/grid/GridPanel.tsx
.storybook/grid/gridStyles.ts
.storybook/grid/register.js
.storybook/grid/withGrid.tsx
.storybook/main.js
.storybook/preview.js
package.json
src/AppBanner/index.stories.tsx
src/DigitalSubscriberAppBanner/index.stories.tsx
src/utils/env.ts
src/utils/images.ts
yarn.lock

Builds on top of #44 by integrating with Grid, allowing the marketing user to select an image from Grid instead of specifying the image manually. As with the other configurable elements, the marketing user would then transfer these to Braze as key/value pairs when configuring an in-app message.
https://trello.com/c/4QSxdwus/994-integrate-grid-picker-with-storybook
Outstanding items, which could be tackled in future PRs:
* Hosted storybooks are still on Chromatic, where the grid picker won't load because of the content security policy. They need to be moved to a gutools.co.uk domain.
* We aren't being smart about which crop size to use, we simply selected the last one on the list. We've talked about extending this to generate a `i.guim.co.uk` URL from the `media.guim.co.uk` url returned by …

Integrate Grid Picker with Storybook

---

artifact.json
bin/ci
cloudformation-static-s3.yaml
package.json
riff-raff.yaml
yarn.lock

Build and deploy Storybook to S3. This is so that we can put Storybook behind a gutools domain in order to embed Grid (added in #49) and abide by Grid's content security policy.
* Added Team City project to build storybook and upload artifacts to Riff Raff
* Cloudform the destination S3 bucket (one time only, this isn't happening on build, but I've added the cloudformation yaml to the repo)
* Configure Riff Raff to deploy to S3 using the `aws-s3` build type

Deploy Built Storybook to S3

---

cloudformation-static-s3.yaml
cloudformation.yaml

Sets up Cloudfront with the relevant access permissions for Storybook in [prod](https://d24910mcsqu03e.cloudfront.net/) and [code](https://d63nzptxc4ib2.cloudfront.net/). We've requested custom domains for PROD and CODE but they aren't ready yet.
PR to setup Riff Raff to do the cloudformation to follow.

Setup Cloudfront for Storybook

---

bin/storybook
package.json
yarn.lock

Running `yarn storybook` locally now correctly opens Storybook on the custom dev-gutools domain we've configured. Previously it would open on localhost:6016 and you'd have to navigate to the custom domain manually in order for the Grid integration to work.
Run `yarn storybook` locally.

Open Storybook on dev-gutools domain

---

package.json
yarn.lock

Bumps the versions of src libs we're using. While developing another banner an issue came up with `LinkButton` which is fixed in later versions of src-button. I agreed with William that we'd bump the version user here and they'd do the same for DCR (better to have fewer versions of dependencies floating around at the same time).
Storybook!

Bump src packages

---

src/BrazeMessage.tsx
src/SpecialEditionBanner/index.stories.tsx
src/SpecialEditionBanner/index.test.tsx
src/SpecialEditionBanner/index.tsx

Adds a new banner to support an editions app message for the end of the year. The turn around on this was tight so we've essentially duplicated `DigitalSubscriberAppBanner` changing the necessary elements.
Storybook!
Note that the body text is likely to be made shorter (controlled by marketing in Braze):

Special Edition Banner

---

package.json
src/AppBanner/index.tsx
src/BrazeMessage.tsx
src/DigitalSubscriberAppBanner/index.tsx
src/SpecialEditionBanner/index.tsx
src/TheGuardianIn2020Banner/index.tsx
yarn.lock

Bumps the `@guardian/types` lib to `v1.1.0`
**This is a breaking change**
The move to `v1` was a breaking change  to the way these types are exported and in order for DCR to upgrade (so that we can use const enums from /types) we need all dependencies to also bump their versions.

Bump @guardian/types to v1.1.0

---

package.json
yarn.lock

Bumps `@guardian/types` to `v2.0.0`
To support enums without having to manage const enums

Bump @guardian/types to v2.0.0

---

.github/workflows/chromatic.yml
.github/workflows/jest.yml
.github/workflows/lint.yml

uses guardian/actions-setup-node
using NVM here installs the correct version of node, but that instance of Node is not then used for the subsequent tasks. this ensures your NVM version is the one the tasks run with.

use guardian/actions-setup-node

---

src/Epic/index.stories.tsx

This updates the `slotName` from "Epic" to "EndOfArticle".

Updated slotName to be 'EndOfArticle'

---

.eslintrc.js

When running `yarn eslint` ignore the `dist` folder.

Eslint should ignore the dist directory

---

src/TheGuardianIn2020Banner/index.tsx

We had previously not included click tracking for The Guardian In 2020 banner as we believed there were Braze tracking issues related to link clicks that redirect to a new page.
However, we have tested link clicks on fast and slow internet connections and found their tracking to be reliable in both cases (click tracking in Braze does not seem to rely on asynchronous requests after the click has occurred, but instead caches the click data locally and sends it to Braze on a subsequent page view).
As our testing has found link click tracking to be reliable, I am adding it to the GuardianIn2020 Banner. Though this banner is no longer live, it is useful to have a banner component where link click tracking is in place as an example for future work, or as a basis for a future banner.
We will …

Add click tracking to GuardianIn2020 banner

---

logic-index.ts
logic/package.json
package.json
rollup.config.js

This adds a second entry point for the package which we'll start using in a future PR for the business logic we're adding to this package. Currently the business logic contains a single placeholder function `add(a: number, b: number): number` as a proof of concept.
On the platforms we can now create two separate bundles, allowing us to lazy load only the code we need.
For the business logic:
```js
import(
/* webpackChunkName: "guardian-braze-components-logic" */ '@guardian/braze-components/logic'
)
.then((module) => {
const add = module.add;
// Do something with add ...
})
```
and for the React components:
```js
import(
/* webpackChunkName: "guardian-braze-components" */ '@guardian/braze-components'
)
.then((module) => {
setBrazeComponent(() => module.BrazeMessage);
})
```

Split Entry Points

---

logic/package.json
tsconfig.types.json

This ensures the correct TS types are available when importing /logic.

Fix types exposed by package

---

src/Epic/index.stories.tsx

The existing epic URL is no longer active.
This moves `braze-components` to its new URL at [https://contributions.guardianapis.com/modules/v1/epics/ContributionsEpic.js](https://contributions.guardianapis.com/modules/v1/epics/ContributionsEpic.js)
This will still need to be updated on the platforms.

Moved to new contributions epic url

---

package.json
rollup.config.js

Instead of relying on dependencies from the window object, these are now resolved in a more conventional way and specified as peer dependencies.
Note that I've already created a release `v0.0.20` from this branch which has been developed against while getting the platforms ready for this change. We'll still need to bring these changes back into main so that future releases work. I'll merge this PR once `0.0.20` is being used on both platforms.
I've merged `main` back into here, and resolved any conflicts. I deliberately didn't rebase because I want to retain the commits I did NPM package releases on (prerelease `0.0.20-0` and `0.0.20`).
Frontend is now using conventional dependencies instead of relying on the window (guardian/frontend#23610). DCR has a PR, not merged yet: …

Don't rely on dependencies on the window object

---

.storybook/gu-preview/GuPreview.tsx
src/Epic/index.stories.tsx

1. Moves from a query string to a URL fragment (i.e. `#force-braze-message={ ... }`)
2. Fixes the data outputted from the Epic story:
The JSON-encoded data in the GU Preview addon URL for the Epic story did not match the format of data expected by the platform when using `force-braze-message`.
The platform expects e.g:
```js
{
heading: data.heading,
highlightedText: data.highlightedText,
buttonText: data.buttonText,
buttonUrl: data.buttonUrl,
componentName: data.componentName,
slotName: data.slotName,
paragraph1: "Lorem ipsum...",
paragraph2: "Dolor sit amet..."
}
```
While we were previously providing:
```js
{
cta: { 
text: data.buttonText, baseUrl: data.buttonUrl 
},
heading: data.heading,
highlightedText: data.highlightedText,
paragraphs: [ "Lorem ipsum...", "Dolor sit amet..."
}
``` …

GU Preview to use URL fragment & reformat Epic story gu-preview output

---

src/Epic/index.stories.tsx

We realised that we need marketing to configure an `ophanComponentId` in the key value pairs sent from Braze which we'll pass with the Ophan view event. It's not passed as a prop to the component but is used on platform. Because marketing use Storybook as the staging ground for key/value pairs and then copy over to Braze, include it in the story:
In working on this we realised that the behaviour of Storybook didn't match the production behaviour on DCR where we [validate that certain props have been provided](https://github.com/guardian/dotcom-rendering/blob/acb093890c93ce6c314106bbe45e634e0be20103/src/web/lib/braze/parseBrazeEpicParams.ts#L45) (via Braze key value pairs) and render nothing if they aren't there. I've added that behaviour to Storybook but it's unfortunate …

Add ophanComponentId knob to Braze epic story

---

rollup.config.js

We moved away from relying on dependencies via the window in #121 but deleting this `const globals` was missed.
`yarn build` runs successfully.

Remove unused variable in rollup config

---

src/logic/BrazeMessages.test.ts
src/logic/BrazeMessages.tsx
src/logic/LocalMessageCache.test.ts
src/logic/LocalMessageCache.tsx

[Related trello card.](https://trello.com/c/9ss9sL1e/1114-actually-start-using-message-caching-on-dcr-and-frontend)
Log error messages from `LocalMessageCache` when messages expire or cannot be added to a full queue. `errorHandler` is provided by the platform (Frontend / DCR) - currently this will log to Sentry on both platforms.
The `errorHandler` must already provided to `BrazeMessages` by the platform (this was already the case).

Add error messages when messages expire or cannot be added to full queue

---

src/Epic/index.stories.tsx

Adds the `ophanComponentId` knob value to the preview link from Storybook. Now that the platform is enforcing that this is provided, without it the epic won't render.
Open the epic story in Storybook and click through to see the preview on preview.gutools.co.uk.

Add ophanComponentId to the preview link

---

src/Epic/index.stories.tsx

Align with the changes in guardian/dotcom-rendering#2927 and relax the prop validation we do (`heading` and `highlightedText` are not required). This ensures that the behaviour marketing seeing when previewing with Storybook will match the way the platform behaves.
Having to update this in two places is clearly not ideal. I think if we keep using this epic component we should stop borrowing from support-dotcom-components and bring the `Epic` component into this repo. Otherwise marketing may decide not to use this format for future end-of-article messages. Either way we'll move away from the support-dotcom-components epic component.
Epic without `heading` or `highlightedText`:

Update prop check to reflect DCR

---

.vscode/settings.json
package.json
yarn.lock

Upgrades the version of TypeScript used by the project to 4.2.4.
`yarn tsc`

Upgrade TypeScript

---

.eslintrc.js
package.json
src/AppBanner/index.tsx
src/AppBanner/styles.ts
src/Epic/index.stories.tsx
src/TheGuardianIn2020Banner/index.tsx
src/TheGuardianIn2020Banner/styles.ts
src/styles/bannerCommon.ts
tsconfig.json
yarn.lock

Upgrades the versions of Emotion and Source we're using. Following https://theguardian.design/2a1e5182b/p/54d9c6-whats-new-in-v300 and https://emotion.sh/docs/emotion-11.
Running `yarn build` gives some warnings:
```./index.ts → dist/index.js, dist/index.esm.js...
(!) Error when using sourcemap for reporting an error: Can't resolve original location of error.
node_modules/@guardian/src-button/dist/esm/index.js: (1:13)
(!) Error when using sourcemap for reporting an error: Can't resolve original location of error.
node_modules/@guardian/src-button/dist/esm/index.js: (1:21)
┌────────────────────────────────┐
│                                │
│   Destination: dist/index.js   │
│   Bundle Size:  50.8 KB        │
│   Minified Size:  50.77 KB     │
│   Gzipped Size:  15.14 KB      │
│ …
```

Emotion 11 & Source 3 Upgrade

---

src/Epic/index.stories.tsx

Updates the epic component loaded from support-dotcom-components in our epic story. This reflects what we're now doing in prod, as of guardian/dotcom-rendering#2994.
The epic story will now load the v2 component, you can see this in the network inspector.
As time goes on, "borrowing" the epic component from source-dotcom-components feels like less of a good idea. It's inconsistent with our other Braze messages and feels more fragile. I'd be keen to bring the epic component fully into this project in future.

Use the v2 ContributionsEpic component

---

.vscode/launch.json

Adds VSCode launch config for debugging tests
Checkout with VSCode. Add a breakpoint to any test file. Click the Run and Debug button on the left hand side. Then choose vscode-jest-tests and click the run button next to that dropdown. This should run the tests and break at your breakpoint to allow debugging.
You can debug tests helping you fix tests faster.
We might spend too long debugging tests and go insane.

Add debug tests to launch.json

---

bin/storybook

Disable cache for local storybook using --no-manager-cache flag.
More documentation here: https://storybook.js.org/docs/riot/api/cli-options﻿

Disable cache for local storybook

---

.storybook/grid/GridPanel.tsx
.storybook/grid/gridStyles.ts
.storybook/gu-auth/GuAuth.tsx
.storybook/gu-auth/register.js
.storybook/main.js
.storybook/preview.js
.storybook/utils.ts
package.json
src/AppBanner/index.stories.tsx
src/utils/env.ts
yarn.lock

* Makes the Grid integration visible by not blocklisting the `AppBanner` component.
* Create a signed image URL by calling the new [image signing service](https://github.com/guardian/image-url-signing-service) when an image URL is received from Grid.
* Checks that the user is logged in on the .gutools.co.uk domain and redirects to login.gutools.co.uk if not (you'll need to be logged in for requests to Grid and the image signing service to work).

Integrate with GuTools login and image signing service

---

src/AppBanner/index.stories.tsx
src/DigitalSubscriberAppBanner/index.stories.tsx
src/Epic/index.stories.tsx
src/SpecialEditionBanner/index.stories.tsx
src/TheGuardianIn2020Banner/index.stories.tsx

We support two slots currently - Banner and EndOfArticle. It makes sense to group components in Storybook by these slots. Also setting the story name to match the component name seems to have the effect of removing an extra layer from the hierarchy which I think makes it simpler to navigate.

Group stories by slot

---

.storybook/utils.ts
bin/storybook
nginx/nginx-mappings.yml

It keeps on confusing me that locally the subdomain for storybook is `braze-storybook` but everywhere else it's `braze-components`. Rename to be consistent with other environments.
* `yarn storybook`
* visit https://braze-components.local.dev-gutools.co.uk/

Rename local storybook host

---

src/Epic/index.stories.tsx

The ContributionsEpic component added some validation to the passed props which we weren’t passing here. Add the missing props in so the component renders correctly.
The epic component renders as expected in storybook.
Before (no epic):
After (an epic):

Fix broken epic rendering

---

package.json
yarn.lock

Bump [`@braze/web-sdk-core`](https://www.npmjs.com/package/@braze/web-sdk-core) NPM package to 3.3.0. This is a dev dependency of this project. We import types in a few
places and also the `appboy` object in a test.
`yarn test`
`yarn tsc`

Bump @braze/web-sdk-core NPM package to 3.3.0

---

src/AUNewsletterEpic/index.stories.tsx
src/AUNewsletterEpic/index.tsx
src/AppBanner/index.stories.tsx
src/BrazeMessageComponent.test.tsx
src/BrazeMessageComponent.tsx
src/DigitalSubscriberAppBanner/index.stories.tsx
src/NewsletterEpic/canRender.ts
src/NewsletterEpic/index.test.tsx
src/NewsletterEpic/index.tsx
src/SpecialEditionBanner/index.stories.tsx
src/TheGuardianIn2020Banner/index.stories.tsx
src/UKNewsletterEpic/index.stories.tsx
src/UKNewsletterEpic/index.tsx
src/USNewsletterEpic/index.stories.tsx
src/USNewsletterEpic/index.tsx

This PR adds support for a `subscribeToNewsletter` prop to the newsletter epic components. This prop has the following type:
```ts
export type NewsletterSubscribeCallback = (id: string) => Promise<void>;
```
The implementation for this prop will be supplied by the platforms. The function is invoked when a user clicks on the "Sign up" button.
Note that the in-progress state and failures states aren't complete yet as we're waiting on design input.

Support clicking on the newsletter sign up button to subscribe

---

src/canRender.ts

Fixes a tiny typo in the `canRender` import for `UKNewsletterEpic` which was preventing that newsletter from being seen as valid by the logic in `BrazeMessages` and so messages with this `componentName` wouldn't be rendered.

Fix UKNewsletter `canRender` import

---

src/NewsletterEpic/index.tsx

Updates the top border colour of the newsletter epic to match the Figma designs.
I've also updated a few places to use colour values from the design system.

Update newsletter epic top border colour

---

src/Epic/index.tsx
src/NewsletterEpic/index.tsx

Removes some horizontal padding from both newsletter and contributions epic components. We noticed when rendered in the context of an article there was some extra whitespace we didn't want.
Newsletter epic example (note the spacing to the left and how the left edge of the component aligns with the article text):

Remove margins from both epics

---

src/NewsletterEpic/index.tsx

This PR contains minor tweaks to the newsletter epic text styles to more closely match the designs in Figma.

Newsletter Epic Text Styling Tweaks

---

src/AUNewsletterEpic/canRender.ts
src/AUNewsletterEpic/index.stories.tsx
src/AUNewsletterEpic/index.tsx
src/NewsletterEpic/canRender.ts
src/NewsletterEpic/index.test.tsx
src/NewsletterEpic/index.tsx
src/UKNewsletterEpic/canRender.ts
src/UKNewsletterEpic/index.stories.tsx
src/UKNewsletterEpic/index.tsx
src/USNewsletterEpic/canRender.ts
src/USNewsletterEpic/index.stories.tsx
src/USNewsletterEpic/index.tsx

This PR contains a couple of tweaks to the `canRender` function(s) of the newsletter epics:
* Make the `ophanComponentId` prop required in all cases, and move it to the key value pairs we get from Braze (as we do for the main contributions epic)
* Validate the `imageUrl` for the top level `BrazeNewsletterEpic` as we do for the `AppBanner` (there was a TODO in there for this which I wanted to get rid of!)

Update newsletter epic `canRender` functions

---

src/AUNewsletterEpic/index.stories.tsx
src/AUNewsletterEpic/index.tsx
src/AppBanner/index.stories.tsx
src/BrazeMessageComponent.test.tsx
src/BrazeMessageComponent.tsx
src/DigitalSubscriberAppBanner/index.stories.tsx
src/Epic/index.stories.tsx
src/Epic/index.tsx
src/NewsletterEpic/index.test.tsx
src/NewsletterEpic/index.tsx
src/SpecialEditionBanner/index.stories.tsx
src/TheGuardianIn2020Banner/index.stories.tsx
src/UKNewsletterEpic/index.stories.tsx
src/UKNewsletterEpic/index.tsx
src/USNewsletterEpic/index.stories.tsx
src/USNewsletterEpic/index.tsx

Previously we had a single factory component `BrazeMessageComponent` which was the entry point for all underlying components, regardless of the slot they're designed for.
Now we have two factory components, one per slot: `BrazeBannerComponent` and `BrazeEndOfArticleComponent`. This has the advantage of having to only pass in the set of props that we might need for the components for a given slot. So we now no longer need to pass `subscribeToNewsletter` to the banner component factory, as none of the underlying components require it.
This opens up the possibility providing separate entry points for each slot, so that when there is a message for the banner slot, we don't also end up lazy loading epic components and vice versa.
I also removed some unused props from the common end of article …

Split banner and epic factories

---

src/Epic/index.tsx

When no highlight text is provided to the braze epic, no empty highlight is shown. This matches the behaviour of the original contributions epic.
In DCR code the text message has no highlight text and shows no highlight.
No empty yellow highlight at bottom of epic paragraphs.

Hide epic highlight if no text provided

---

package.json

Moves `dialog-polyfill` from `dependencies` to `devDependencies` - it's used by one of our storybook plugins. I noticed in guardian/dotcom-rendering#3209 that it ended up being pulled into the `yarn.lock` for that project which is potentially confusing/not what we want.

Package dialog-polyfill should be a devDependency

---

src/Epic/index.stories.tsx
src/Epic/index.tsx

We have use cases where there are links in the paragraph text. Before this change any HTML in the paragraph was escaped. This change makes us behave the same as the RRCP component which we’re switching away from.
Also add a link to the default props in storybook so that if this breaks in future Chromatic will let us know.
Storybook.

Support HTML in paragraphs

---

package.json
src/BrazeBannerComponent.ts
src/BrazeEndOfArticleComponent.ts
src/NewsletterEpic/index.tsx
src/logic/BrazeMessages.test.ts
src/logic/LocalMessageCache.test.ts
yarn.lock

Move @guardian libs from dependencies into peer dependencies. This reduces bundle size loaded by the user as dotcom-rendering and frontend are loading the libraries anyhow, so before this change we were loading them twice for no good reason. 
Run yarn build and check bundle sizes are reduced. yarn link from dotcom rendering and check the components still work. 
Reduced bundle size.
Need to make sure we keep our peerDependencies updated as dotcom rendering and frontend update their libraries.
No UI changes.

Move guardian dependencies to peer dependencies. This reduces bundle size.

---

src/Epic/canRender.ts
src/Epic/placeholders.test.ts
src/Epic/placeholders.ts

Fix the invalid placeholder detection logic and also added some tests as documentation. Previously the code to determine
whether there were any invalid placeholders was always returning false, this fixes the check so that invalid placeholders are correctly flagged.
The fields we support placeholder replacement in are the paragraphs and highlightedText. Update the call to `containsNonAllowedPlaceholder` in the canRender to reflect this.
`yarn test`
You can also try out different placeholders in storybook. If an invalid one is used in the paragraphs or highlighted text the component won't render.

Fix invalid placeholder detection logic

---

src/Epic/index.stories.tsx
src/ExternalEpic/index.stories.tsx

Move Epic component story our of work-in-progress. We're now using the new component in production. Move the old
ExternalEpic to deprecated for now. It feels like there might be occassions where it's useful to have this side by side with our Epic for now. We can probably remove in future.

Move Epic component story out of work-in-progress

---

src/Epic/index.stories.tsx

For components in storybook we offer the ability to preview in place on the preview site via a custom Storybook plugin. This requires a little bit of wiring and it turns out we were missing it for the `Epic` component (I noticed this while attempting to troubleshoot an issue, which this would have made easier).
Run storybook and click on the preview icon:

Fix Storybook Gu Preview link for Epic

---

src/AUNewsletterEpic/index.stories.tsx
src/UKNewsletterEpic/index.stories.tsx
src/USNewsletterEpic/index.stories.tsx

Moves the newsletter epic stories out of `WorkInProgress` as they are now ready to use.

Newsletter epic stories no longer work-in-progress

---

jest.config.js

Fixes a warning from jest. There were previously multiple instances of:
```
ts-jest[config] (WARN) The option `tsConfig` is deprecated and will be removed in ts-jest 27, use `tsconfig` instead
```

Fix a warning emitted by jest

---

src/BrazeEndOfArticleComponent.ts
src/Epic/canRender.test.ts
src/Epic/canRender.ts
src/Epic/index.tsx
src/EpicWithSpecialHeader/canRender.ts
src/EpicWithSpecialHeader/index.stories.tsx
src/EpicWithSpecialHeader/index.tsx
src/canRender.ts
src/storybookCommon/argTypes.ts

This PR adds a new component `EpicWithHeaderImage`. The new component is implemented on top of the existing Epic component and adds a new header section including a headshot and some additional text.
This PR supersedes #222. It turned out the image marketing wanted to use was very text heavy, which didn't feel like a great fit (accessibility concerns, as well as general inflexibility of delivering text in an image).
Note: The entire new top section is hidden on mobile.
We’re treating our first usage of the epic with an image as an experiment, so short term we’ll hardcode the text and image to avoid the overhead of adding proper image support (via the picker). If the test goes well we can make all this a properly supported part of the Epic component. …

Add EpicWithSpecialHeader

---

src/EpicWithSpecialHeader/index.stories.tsx

The version of braze-components which introduces `EpicWithSpecialHeader` is now being used by DCR, so we can take this out of work-in-progress.

Move EpicWithSpecialHeader out of work-in-progress

---

src/AUNewsletterEpic/index.tsx
src/UKNewsletterEpic/index.tsx
src/USNewsletterEpic/index.tsx

Updates the image transformation params we're using for newsletter epic images.
From talking to other developers who understand the image transformation service well, we should always be using the master crop as the source for image transformations.
I've also added in the quality and auto=format params. Auto format does causes the image transformation service to do the right thing with regards to converting to either webp or png8.
My goal when looking at the transformations we were applying was to see if I could get the image size down any further, which I wasn't successful in doing. Of the three images two a very marginally smaller and one is very marginally larger than what we had before. I think we should merge this anyway as it's slightly more correct than what we had previously. …

Use master crop image source for transformations

---

cloudformation.yaml

Reduces the min (and now max) TTL for the cache on the cloudfront used to host braze-components.gutools.co.uk from 1 hour to 1 minute. This reduces the time it takes to confirm that a change is in production storybook which is really helpful when deploying hotfixes. 
https://trello.com/c/LVCDMM2l/1236-revisit-braze-componentsgutoolscouk-caching-strategy
Make a change to braze components and check that it shows up in a few minutes as opposed to an hour. Also check the network tab for a changed cache control header.
Changes to braze components show up in a few minutes as opposed to an hour.
This will reduce the use of the cache slightly. Given this is an internal low traffic site the reduced cache hit's shouldn't be a problem.

Reduce TTL on cloudfront cache to 1 minute

---

package.json
src/logic/BrazeMessages.test.ts
src/logic/BrazeMessages.tsx
src/logic/LocalMessageCache.tsx

https://trello.com/c/d5NYSNVi/1250-update-guardian-braze-components-to-filter-by-section
Adds article context filtering (worked on by Tom Wey as part of team hack day) to the braze components message cache. When we receive a message from Braze that should trigger a component being displayed on the page we store in in a local storage cache. With this change we only show messages from the cache if they match the article context (otherwise they stay in the cache).
For example if the braze message has the field section with value 'environment' the message will only be shown on articles in the environment section.
The only change here from the hack day code is an interface called BrazeArticleContext is passed to the braze cache logic instead of the section directly. This is to support more …

Article context filtering (section only)

---

src/BrazeEndOfArticleComponent.ts
src/DownToEarthNewsletterEpic/canRender.ts
src/DownToEarthNewsletterEpic/index.stories.tsx
src/DownToEarthNewsletterEpic/index.tsx
src/canRender.ts

Adds the down to earth newsletter epic component
https://braze-components.code.dev-gutools.co.uk/?path=/story/endofarticle-downtoearthnewsletterepic--default-story

Down to earth newsletter epic

---

cdk/lib/__snapshots__/braze-components.test.ts.snap
cdk/lib/braze-components.ts

In #263 we opted out of @gu/cdk tagging to reduce the size of the diff with our previous cloudformation.yaml. This adds the tagging back in.

Opt back into gu/cdk tagging

---

cdk/lib/__snapshots__/braze-components.test.ts.snap
cdk/lib/braze-components.ts

Adopt our existing DNS setup into CDK. As we've lined the configuration up exactly, this won't actually cause any changes.
We've deployed to `CODE`: https://braze-components.code.dev-gutools.co.uk/

Adopt DNS provisioning into CDK

---

package.json
yarn.lock

Bumps the version of @guardian/node-riffraff-artifact used.

Upgrade @guardian/node-riffraff-artifact

---

cdk/lib/__snapshots__/braze-components.test.ts.snap
cdk/lib/braze-components.ts
cdk/package.json

Create a Cloudfront Distribution in our CDK, wiring it up with the existing static bucket and access origin ID.
Deploy via Riff Raff and visit the Cloudfront URL.

Create new Cloudfront Distribution in CDK

---

cdk/lib/__snapshots__/braze-components.test.ts.snap
cdk/lib/braze-components.ts

Sets the DNS TTL back to 1 hour. We'd previously reduced this to 1 minute while we were making changes to
give us flexibility in case we broke anything.

Set TTL back to 1 hour

---

src/BannerWithLink/index.stories.tsx
src/BannerWithLink/index.tsx
src/BannerWithLink/styles.ts

This PR updates the `BannerWithLink` colours to the designs from marketing for the Gu in 2021 moment.
I made a couple of simplifications along the way to accommodate the new colours, for example:
* Removed the hover effect on the close button and main link button
* Simplified the info icon to be a single colour with transparent background
The changes are deployed to the [CODE storybook](https://braze-components.code.dev-gutools.co.uk/?path=/story/workinprogress-banner-bannerwithlink--default-story).

BannerWithLink style tweaks

---

src/BannerWithLink/index.stories.tsx
src/BannerWithLink/index.tsx
src/BannerWithLink/styles.ts
src/styles/bannerCommon.ts

This PR tweaks the styling around the image a little bit, resulting in less empty space (requested by design). I've tried to balance the changes to ensure they work generally, across different image sizes we might use for this banner, rather than focusing solely on the image for the Gu in 2021 campaign.
The changes are deployed to the [CODE storybook](https://braze-components.code.dev-gutools.co.uk/?path=/story/workinprogress-banner-bannerwithlink--default-story).
Also, see the Chromatic diff.
At desktop width, with the default image:

BannerWithLink image tweaks

---

src/BannerWithLink/index.stories.tsx

Move the `BannerWithLink` component out of the work-in-progress folder in storybook. This PR can be merged once guardian/dotcom-rendering#3843 and guardian/frontend#24567 have been merged/deployed.
Run storybook locally.

Move BannerWithLink out of work-in-progress

---

package.json
src/AUNewsletterEpic/index.stories.tsx
src/BrazeEndOfArticleComponent.ts
src/DownToEarthNewsletterEpic/index.stories.tsx
src/Epic/index.stories.tsx
src/EpicWithSpecialHeader/index.stories.tsx
src/UKNewsletterEpic/failure.stories.tsx
src/UKNewsletterEpic/index.stories.tsx
src/USNewsletterEpic/index.stories.tsx

We'd like to start tracking clicks in our epic components, like we do for our banner components. This is primarily so that we can control Braze canvas progression based on buttons clicked.

Add click handlers to `BrazeEndOfArticleComponent` interface

---

src/NewsletterEpic/index.tsx

Use `SvgClock` icon from source-react-components instead of inlining. This was left over from wanting to use the icon before it had been added to source.
Chromatic shouldn't show any visual differences.

Use SvgClock icon from source-react-components

---

src/AUNewsletterEpic/index.tsx
src/DownToEarthNewsletterEpic/index.tsx
src/NewsletterEpic/index.test.tsx
src/NewsletterEpic/index.tsx
src/UKNewsletterEpic/index.tsx
src/USNewsletterEpic/index.tsx

Now when a reader clicks on the subscribe button on any of our newsletter epic components, the event will be reported to Ophan and Braze.

Wire click handlers with newsletter epic subscribe button

---

src/AUNewsletterEpic/index.tsx
src/BrazeBannerComponent.ts
src/BrazeEndOfArticleComponent.ts
src/DownToEarthNewsletterEpic/index.tsx
src/Epic/ContributionsEpicButtons.tsx
src/Epic/index.stories.tsx
src/Epic/index.test.tsx
src/Epic/index.tsx
src/NewsletterEpic/index.test.tsx
src/NewsletterEpic/index.tsx
src/UKNewsletterEpic/index.tsx
src/USNewsletterEpic/index.tsx
src/buildBrazeMessageComponent.test.tsx
src/buildBrazeMessageComponent.tsx
src/utils/tracking.test.tsx
src/utils/tracking.ts

This PR builds on #303 by wiring up the tracking on the Remind Me button (which is essential, so that we can know to schedule the email in Braze when a user clicks).
I was finding that the detail of all of our underlying components knowing about `submitComponentEvent` (Ophan) and the Braze tracking callback, which are both provided by the platform, a bit unwieldy. The underlying components always just trigger both, and that logic was duplicated in multiple places. More importantly, I don't think the underlying components should care about this level of detail.
So this PR also includes a refactoring where the higher-level entry component for each slot (`BrazeEndOfArticleComponent` and `BrazeBannerComponent`) takes the two click handling functions and combines them into a single callback …

Epic Remind Me Button Tracking

---

package.json
src/AUNewsletterEpic/index.tsx
src/BrazeBannerComponent.ts
src/BrazeEndOfArticleComponent.ts
src/DownToEarthNewsletterEpic/index.tsx
src/Epic/ContributionsEpicButtons.tsx
src/Epic/RemindMeConfirmation.tsx
src/Epic/index.stories.tsx
src/Epic/index.test.tsx
src/Epic/index.tsx
src/NewsletterEpic/index.test.tsx
src/NewsletterEpic/index.tsx
src/UKNewsletterEpic/index.tsx
src/USNewsletterEpic/index.tsx
src/buildBrazeMessageComponent.test.tsx
src/buildBrazeMessageComponent.tsx
src/utils/tracking.test.tsx
src/utils/tracking.ts
yarn.lock

This add the remind me button to the Braze `Epic` component.
We've introduced 3 new (optional) props/values to be passed from Braze:
* `remindMeButtonText`
* `remindMeConfirmationText`
* `remindMeConfirmationHeaderText`
If all three are specified, we'll render the remind me button.
As well as the dynamic/configurable confirmation text, we also include some hardcoded privacy text (supplied by Gavin).
~~Note that I've not included the click tracking for these epic buttons yet. I'm working on that in a separate branch as I'm experimenting with an approach which requires some refactoring and I didn't want this PR to get too big. We wouldn't want to use the remind me button as it's implemented in this PR until the tracking is done (as we wouldn't know when a user has clicked the button, and to …

Add Epic remind me button

---

src/Epic/RemindMeConfirmation.tsx

This is a minor copy change. When a user clicks "Remind Me" on the Contribution epic there is a piece of dynamic text followed by a preset piece of content with links to our email preference management area. This PR changes that preset text and link.
The content has changed in storybook, the link follows through to the correct place and the dynamic text is still changable.

Change Remind Me confirmation text

---

src/Epic/index.stories.tsx

* Adds some missing Storybook docs for the primary epic `buttonUrl` prop.
* Document the ID with which epic button clicks will show up with in Braze (there was some confusion over this with marketing recently, and I realised this information isn't surfaced to them anywhere).
Run storybook locally.

Small Storybook epic button docs improvements

---

package.json
yarn.lock

Resolves minimist to 1.2.6. The minimist package has a security vulnerability fixed in 1.2.6. This package is pulled in by a number of our transitive dependencies, which haven't necessarily upgraded to bump minimist. So ensure they all resolve to 1.2.6 for now.

Resolve minimist to 1.2.6

---

yarn.lock

Upgrade the `async` NPM package to v2.6.4. 2.6.4 fixes a security issue.

Upgrade async NPM package

---

.storybook/article-context/ArticleContextPanel.tsx

In #362 we added support for specifying that a message should appear on multiple sections (previously there was a limitation to a single section). This PR updates the storybook `Article Context Filters` tab to make it clear multiple sections are supported. When multiple sections are selected a pipe (`|`) separated list is generated which can be copy pasted into Braze.
In future it might be nice to use a fancier multi-select component, but for now I'm keeping it simple and going with the basic HTML version.

Storybook Multi-section Filter

---

cdk/yarn.lock

Upgrades the vm2 library, which is a transitive dependency of `@guardian/cdk`. Dependabot flagged a security alert for this package.
```
$ cd cdk
$ yarn test
```

Upgrade vm2 to 3.9.11

---

package.json
src/AppBanner/index.tsx
src/BannerWithLink/index.tsx
src/styles/bannerCommon.ts
yarn.lock

DCR is upgrading `@guardian/source-*` libs. We rely on the platform providing source libs as peerDependencies. Bump the versions in here so we match what DCR is providing (there's an open question of what to do for frontend, which we are also consumed by, and which hasn't upgraded source libs yet).
Storybook & Chromatic. Note that there are still some Chromatic diffs being reported, but they look minimal so I think are fine to accept.

Source package upgrades

---

src/AppBanner/index.tsx
src/BannerWithLink/index.tsx
src/utils/useEscapeShortcut.ts

Adds functionality which will allow users to close the Braze banner by pressing on the keyboard ESC key - this matches existing functionality for closing RRCP banners
The PR also includes a small fix to make the page focus revert to `document.body` when the user closes the banner.
Test in Storybook by opening a banner then clicking on the ESC key

Close the banner when user presses the ESC key

---

yarn.lock

Upgrades the `loader-utils` npm package. Dependabot reported a vulnerability.

Upgrade loader-utils

---

yarn.lock

Upgrade loader-utils v2. Dependabot reported a vulnerability.

Upgrade loader-utils v2

---

src/logic/BrazeCards.ts

The `logCardImpressions` method takes an optional second boolean argument. This determines whether to log the impression as a content card event (as opposed to a legacy news feed event, which is apparently a predecessor to content cards).

Log impressions as content cards

---

src/Epic/index.tsx

The style of `<b>` tags is being overridden by DCR, causing them to have no effect.
We made a [similar change in SDC](https://github.com/guardian/support-dotcom-components/pull/806)

Fix bold in epic

---

package.json
src/Epic/RemindMeConfirmation.tsx
yarn.lock

We rely on both `@guardian/source-react-components-development-kitchen` and `@guardian/libs` as peer dependencies, provided by the web platforms.
This PR loosens the peer dependencies for both and updates the dev dependency to the latest version.

Bump `@guardian/source-react-components-development-kitchen` and `@guardian/libs`

---

src/canRender.ts

A small update to make sure the new Newsletter Epic templates created in #385 will be rendered to End Users when required.

Fix canRender file to include new Newsletter Epic templates

---

.storybook/gu-preview/GuPreview.tsx
.storybook/utils.ts

In storybook there's a button in the header to preview the components in place on the preview site. The CODE instance of storybook links to prod preview but it feels more useful to link to code preview.
Click the button in CODE storybook and the component will render in CODE preview.

Link CODE storybook to CODE preview for previewing rendering

---

package.json
yarn.lock

Upgrade @guardian/libs@^14.0.0
Following some dep updates this is now the last peer dep error for https://github.com/guardian/frontend/pull/25892

Upgrade @guardian/libs@^14.0.0

---

src/EpicWithSpecialHeader/canRender.ts

When we updated the epicWithSpecialImage header we accidentally left out the check which determines whether the supplied image url comes from a permitted Guardian source. This PR rectifies the situation
Test in Storybook

Legitimate image url check for epics

---

package.json
yarn.lock

Upgrades the version of `np` used to publish releases.
I published a pre-release from this branch which seems to have worked.
Previously Rik discovered that releasing had been broken since the Node upgrade, as under the hood `np` was relying on an `npm` command which no longer exists.
-   [ ] [The change doesn't use only colour to convey …

Upgrade `np`

---

README.md

Updates the README "releasing to NPM" section with a note about a potentially confusing message which is sometimes shown by the `yarn release` script.

Update README releasing to NPM section

---

src/Epic/ContributionsEpicButtons.tsx
src/StyleableBannerWithLink/index.stories.tsx
src/StyleableBannerWithLink/index.tsx
src/styles/bannerCommon.ts

A small update to the new styleable banner which will allow Marketing colleagues to add the payment icons to the main CTA button

Add card payment symbols option to styleable banner CTA button

---

cdk/package.json
cdk/yarn.lock

Upgrade the version of `@guardian/cdk` we're using. This fixes an issue raised by Snyk for aws-cdk-lib as we're forced to bump that library as it's a peer dependency of gu cdk (which requires a later version).
The CDK in this project handles provisioning of AWS resources for the hosted Storybook instance, so to test I've deployed to CODE and checked the hosted storybook still works. Note: the cloudformation update was quite slow, apparently that's normal when we're touching cloudfront distributions.
-   [ ] [Colour …

Upgrade @guardian/cdk

---

src/Epic/index.tsx
src/StyleableBannerWithLink/index.tsx
src/components/ContributionButtonWithReminder.tsx
src/components/PaymentIcons.tsx
src/components/ReminderCtaConfirmation.tsx

This small PR reorganises some components that are about to be shared between Braze Epics and Banners (principally the contributions-with-reminders buttons) into a new `components` folder
Storybook should be sufficient
I suggest we don't publish the repo after this PR is merged into main?

Refactor components in preparation for reminders work

---

src/AppBanner/index.tsx
src/StyleableBannerWithLink/index.tsx
src/styles/bannerCommon.ts

Marketing reported 2 issues with the new styleable banner:
1 - the image does not center
2 - the highlighted text background color expands to fill the block rather than just highlight the text
We need to fix these issues so they can release a banner as part of the new Europe edition launch
**Before fix**
**After fix**

Styleable banner hotfixes

---

src/AppBanner/index.tsx
src/BannerWithLink/index.tsx

This updates the markup in BannerWithLink and AppBanner to match StyleableBannerWithLink so that the shared styling is applied in the same way. Previously after #424 was merged we lost a bit of spacing between the body text and highlighted text on other banners as the container didn't exist in the markup.
Storybook!
-   [ ] [The change doesn't use only colour to convey …

Fix spacing on BannerWithLink and AppBanner

---

README.md

Updates the README to use [`yalc`](https://github.com/wclr/yalc) for integrating local/unpublished braze-components with a consuming project, e.g. DCR.

Update local DCR instructions to use `yalc`

---

.github/workflows/braze-components.yml

This adds a new step to the main GHA workflow to run `yarn changeset publish`.
When a PR is merged which is part of a changeset, a new PR will be automatically opened to create the new release. When this PR is merged to main, the new release will be published to NPM. If the release PR is not merged and subsequent PRs are merged with a changeset specified, the release PR will be updated.
-   [ ] …

Publish to NPM from CI

---

src/Epic/index.tsx
src/StyleableBannerWithLink/index.tsx
src/components/PrimaryCtaButton.tsx

Instead of casting, acknowledge that these user provided button colours might be missing and let the type guard used by `getColors` handle this. The return value from `getColors` is guaranteed to have legit `ColorValueHex` values.
I've decoupled the `getColors` logic (combine user provided styles with defaults, in case any user provided styles are missing or invalid) and the logic to take the colours and convert them to styles.
I've focused on the PrimaryCtaButton here, but the pattern could be applied to all components which support user provided styles.
This should be purely a refactoring and shouldn't change the Chromatic snapshots at all, compared with the based branch.
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visu …

Avoid casting user provided styles for `PrimaryCtaButton`

---

.changeset/itchy-pants-flash.md
src/AUNewsletterEpic/index.tsx
src/EpicNewsletter_AU_AfternoonUpdate/index.tsx

A tiny update to refresh the images used in the 2 Australian newsletter epics
Checking in Storybook should be sufficient

Update Aus newsletter epic images

---

.changeset/pink-apes-destroy.md
src/logic/reminders.ts
src/utils/env.ts

While attempting to test the reminders work from #433 and #422 in CODE I ran into an issue which was preventing the reminder sign-up from working. In the code we attempt to check whether we're running in Storybook, in which case we return a stub promise which immediately resolves. However, in the context of DCR `process.env` isn't available so the attempt to read `process.env.STORYBOOK` always fails and causes an error, resulting in the attempt to create the reminder failing. This change allows us to detect storybook in a way that's safe to do in DCR.
I've tested locally running DCR and publishing braze-components with yalc. I see that the reminder signup from the banner now works:
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology …

Fix error when `createReminder` is called

---

.changeset/lovely-dingos-teach.md
logic-index.ts
src/logic/BrazeMessages.test.ts
src/logic/BrazeMessages.ts
src/logic/canRender.ts

The `canRender` function is now passed to the `BrazeMessages` constructor instead of importing directly. This is to facilitate pulling components (which will be co-located with their individual `canRender`) gradually over to DCR. Instead of `BrazeMessages` being able to access `canRender` directly, it will be provided by the caller. For the first pass we'll be passing back in the exact function we currently reference directly. But as components are migrated to DCR we'll have to layer in their own can render behaviour.
- …

Add canRender to BrazeMessages constructor interface

---

.changeset/moody-melons-exist.md
package.json
yarn.lock

Upgrade `@babel/traverse` which dependabot is reporting a vulnerability for.
(Also includes bumping some storybook libs and `@babel/core`).
All `@babel/traverse` usages are satisfied by the same version (`2.23.9`) now.

Upgrade @babel/traverse

---

.changeset/honest-tomatoes-type.md
package.json
src/AppBanner/index.tsx
src/components/ReminderCtaButton.tsx
yarn.lock

- Bumps `@guardian/source-react-components` to [`v22.1.0`](https://github.com/guardian/csnx/releases/tag/%40guardian%2Fsource-react-components%4022.1.0)
- Bumps `@guardian/source-react-components-development-kitchen` to [`v19.0.0`](https://github.com/guardian/csnx/releases/tag/%40guardian%2Fsource-react-components-development-kitchen%4019.0.0)
This is a major change [as per our recommendations](https://github.com/guardian/recommendations/blob/main/npm-packages.md#changes-to-peerdependencies-ranges-are-breaking), and consumers should ensure that they provide a compatible version of the package.
Not sure, left as an exercise to the team
Stop having [mismatched peer dependencies in `dotcom-rendering`](https://github.com/guardian/dotcom-rendering/issues/6945)
```sh
$ pnpm install …
```

Bump `@guardian/*` packages

---

cdk/yarn.lock
package.json
yarn.lock

Vulnerabilities have been reported for the transitive dependencies `braces` and `multimatch`. This PR bumps them both. In most cases new (non-vulnerable) versions satisfied the existing dependency range.
In one case much older versions were being pulled in by `@storybook/preset-typescript`, but this no longer seems to be used so I've removed it.
-   [ ] [The change doesn't use only colour to …

Bump multimatch and braces deps

---

cdk/yarn.lock
yarn.lock

Upgrade json5 npm package. Dependabot has flagged a vulnerability in the following range: `>= 2.0.0, < 2.2.2`.

Upgrade json5 (main project and cdk sub-project)

---

yarn.lock

Bump the http-cache-semantics npm package (a transitive dependency pulled in through a rollup plugin). Dependabot flagged a vulnerability on versions < 4.1.1.

Bump http-cache-semantics

---

yarn.lock

Upgrade axios and follow-redirects NPM packages. Both have had vulnerabilities reported by dependabot. I've grouped these as follow-redirects is a dependency of axios.

Upgrade axios and follow-redirects

---

cdk/yarn.lock
yarn.lock

Upgrade the `ws` NPM package to fix a couple of dependabot alerts.

Upgrade ws NPM package

---

.changeset/healthy-elephants-own.md
package.json
yarn.lock

Broaden the `@guardian/source` peer dep range from `^1.0.1` to `>= 1.0.1 < 7`. I've tested with v6 and the component rendering looks good (I've made an assumption that things are fine in the intermediate major versions too).
As per our recommendations I've bumped the dev version to the latest acceptable.
Check that Chromatic is happy.
-   [ ] [The change doesn't use only colour to convey …

Broaden @guardian/source peer dep requirements up to v6

---

.changeset/perfect-dolls-jump.md
package.json
src/AppBanner/index.tsx
src/Epic/HeaderSection.tsx
src/Epic/index.tsx
src/NewsletterEpic/index.tsx
src/StyleableBannerNewsletter/index.tsx
src/StyleableBannerWithLink/index.tsx
src/components/NewsletterCtaButton.tsx
src/components/NewsletterFrequencyBlock.tsx
src/components/PrimaryCtaButton.tsx
src/components/ReminderCtaButton.tsx
yarn.lock

DCR will [soon be upgrading](https://github.com/guardian/dotcom-rendering/pull/12342) to source 8.
The changes here are:
1. use `cssOverrides` instead of `css` prop
2. replace legacy foundations imports. I used these mappings to help with this: https://gist.github.com/jamesmockett/284f442762360e103c14bd83f90ba4dd

Use source 8

---

cdk/lib/__snapshots__/braze-components.test.ts.snap
cdk/package.json
cdk/yarn.lock

Major version update to "@guardian/cdk" alongside a new resolutions block in the package.json file on order to fix a vulnerability in cross-spawn.
Additional updates to 
- aws-cdk
- aws-cdk-lib
- constructs
- jest
- prettier
- ts-jest
- ts-node

CDK cross-spawn vulnerability fix and dependency updates

---

cdk/lib/__snapshots__/braze-components.test.ts.snap
cdk/lib/braze-components.ts

This adds the `securityPolicy` property to CloudFront for the hosted storybook, and sets it to the highest options `TLS_V1_2_2018`. This will stop it from allowing insecure TLS ciphers.
Tested in CODE and PROD (as Grid integration doesn't work in CODE)

Add security policy property to CloudFront

---

package.json

This PR modifies the version specification for the @braze/web-sdk package in package.json by changing from a caret version range (^5.8.1) to an exact version (5.8.1). While this doesn't change the actual version being used, it enforces that this specific version will be installed rather than allowing compatible updates within the same major version.
1. Delete your node_modules directory and package-lock.json
2. Run npm install to verify the exact version 5.8.1 is installed
3. Run your application's test suite to ensure all Braze SDK functionality continues to work as expected
4. Verify that no unexpected console warnings or errors appear related to the Braze SDK
- Build passes without errors
- No regressions in Braze SDK functionality
- Consistent dependency installation across …

Fixed @braze/web-sdk version

---

yarn.lock

This PR updates the version specification for the `@braze/web-sdk` package in the yarn.lock file, changing from a caret version range (`^5.8.1`) to an exact version (`5.8.1`). This change ensures that yarn will lock to precisely version 5.8.1 rather than potentially accepting minor version updates within the 5.x range.
1. Delete your node_modules directory
2. Run `yarn install` to verify the exact version 5.8.1 is installed
3. Check the installed version with `yarn list @braze/web-sdk` to confirm version 5.8.1
4. Run your application's test suite to ensure all Braze SDK functionality works as expected
5. Verify no unexpected warnings or errors appear in the console related to the Braze SDK
- Successful yarn installation without conflicts
- Consistent dependency versioning across all …

Update @braze/web-sdk Package Configuration in yarn.lock

---

cloudformation-static-s3.yaml

This updates the cloudformation file for the Storybook S3 bucket so that the bucket blocks all public access. There is a global setting on the AWS account already blocking public access, but the fact the bucket itself isn't specifically blocking public access is reported as a vulnerability.
There is CloudFront in front of the bucket so the bucket doesn't need to allow public access.
Once this goes out it should remediate one of the reported FSBP vulnerabilities.
| Before | After |
| --- | --- |
|  <img width="804" alt="image" src="https://github.com/user-attachments/assets/7e7ea17d-81a5-4ec1-8129-24d6c231eebd" /> | ![image](https://github.com/user-attachments/assets/044a4ba3-4bd5-4124-9cf8-3ec132d91564) |
The cloudformation is not part of CI/CD and is deployed manually. We may want to …

Block public access to storybook S3 bucket
